### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by RickvanB** [megawubs/ns-api#1]
Hi,

Any plans for supporting Laravel 5.5? 

I'm not able to install it with Composer.
**I got this message:** 

_Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Can only install one of: nesbot/carbon[1.18.0, 1.22.1].
    - Can only install one of: nesbot/carbon[1.22.1, 1.18.0].
    - Can only install one of: nesbot/carbon[1.18.0, 1.22.1].
    - wubs/ns-api 0.0.13 requires nesbot/carbon 1.18.0 -> satisfiable by nesbot/carbon[1.18.0].
    - Installation request for wubs/ns-api ^0.0.13 -> satisfiable by wubs/ns-api[0.0.13].
    - Installation request for nesbot/carbon (locked at 1.22.1) -> satisfiable by nesbot/carbon[1.22.1]._

**Comment by megawubs** [comment]
I just released a fix for this. When you retry it should use version `1.0.0`

**Comment by RickvanB** [comment]
Thanks! One small question, is it possible to get ticket prices with your API?

**Comment by megawubs** [comment]
I have no idea anymore. It's been quite a while since I used it.

**Comment by RickvanB** [comment]
Hmm alright, I will have a look then. I installed your library and followed the installation instructions. But when I try to use the facade it says that it's not found? Did I miss something?

**Comment by megawubs** [comment]
How do you call the facade? are you using it inside a namespace? If so, you have to import it from the global namespace. To do this, add  `use NS;` to the top of your file.

If this does not work, it's probably broken.

**Comment by megawubs** [comment]
Any success using this package?

Just out of curiosity, do you need this package for a school project at Windesheim?

**Comment by RickvanB** [comment]
No, I don't need this package for a school project. I got it working, however it does not show ticket prices unfortunately.
